model = "gpt-4.1"
model_provider = "openai-chat-completions"

[model_providers.openai-chat-completions]
name = "OpenAI using Chat Completions"
base_url = "https://api.openai.com/v1"
env_key = "OPENAI_API_KEY"
wire_api = "responses"

[features]
rmcp_client = true

[mcp_servers.filesystem]
url = "http://localhost:3000/mcp"
startup_timeout_sec =  30
tool_timeout_sec = 30